FusionManager/Controllers/PersonaController.cs
using FusionManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FusionManager.Controllers
{
    public class PersonaController : Controller
    {
        private readonly IPersonaRepository repository;

        public PersonaController(IPersonaRepository repository)
        {
            this.repository = repository;
        }

        // GET: Persona
        public ActionResult Index()
        {
            var personaList = repository.GetPersonaList();
            return View(personaList);
        }

        public ActionResult Details(string name)
        {
            var persona = repository.GetPersonaByPersonaName(repository.ConvertToStringFromBase64(name));
            return View(persona);
        }

        public ActionResult CompendiumIndex()
        {
            var compendiumList = repository.GetCompendiumList();
            return View(compendiumList);
        }

        public ActionResult CompendiumDetails(string name)
        {
            Persona persona = repository.GetPersonaByPersonaName(repository.ConvertToStringFromBase64(name));

            if(persona.HasCompendiumEntry)
            {
                var model = repository.GetCompendiumEntry(persona.Name);                
                return View(model);
            }
            else
            {
                return CompendiumEdit(name);
            }            
        }

        public ActionResult CompendiumEdit(string name)
        {
            CompendiumEntryModel model = new CompendiumEntryModel();
            CompendiumEntry entry = new CompendiumEntry();

            if (!String.IsNullOrEmpty(name))
            {
                Persona persona = repository.GetPersonaByPersonaName(repository.ConvertToStringFromBase64(name));

                if (persona.HasCompendiumEntry)
                {
                    entry = repository.GetCompendiumEntry(persona.Name);
                    model.InheritedSkills = persona.InheritedSkills;
                }
                else
                {
                    entry.PersonaName = persona.Name;
                    entry.ActualLevel = persona.ActualLevel;
                }
            }
            else
            {
                model.PersonaNames = repository.GetPersonaNames(false);
            }

            model.Entry = entry;

            return View(model);           
        }
    }
}

FusionManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")    
    @Scripts.Render("~/bundles/modernizr")    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fusion Manager", "Index", "Persona", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Compendium", "CompendiumIndex", "Persona")</li>
                    <li>@Html.ActionLink("Fusion", "FusionIndex", "Persona")</li>
                    <li>@Html.ActionLink("Skills", "SkillsIndex", "Persona")</li>
                    <li>@Html.ActionLink("Inheritance", "InheritanceIndex", "Persona")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>